#!/bin/bash
clear
    info2 () {
    clear 
    clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m            USUARIOS REGISTRADOS | UUID V2RAY             \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    # usersss=$(cat /etc/SSHPlus/RegV2ray|cut -d '|' -f1)
    # cat /etc/SSHPlus/RegV2ray|cut -d'|' -f3
    VPSsec=$(date +%s)
    local HOST="/etc/SSHPlus/RegV2ray"
    local HOST2="/etc/SSHPlus/RegV2ray"
    local RETURN="$(cat $HOST|cut -d'|' -f2)"
    local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
    if [[ -z $RETURN ]]; then
    echo -e "----- NENHUM USUARIO REGISTRADO -----"
    echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
    fun_v2raymanager
    else
    i=1
    echo -e "\e[97m                 UUID                | USER | EXPIRACION \e[93m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    while read hostreturn ; do
    DateExp="$(cat /etc/SSHPlus/RegV2ray|grep -w "$hostreturn"|cut -d'|' -f3)"
    if [[ ! -z $DateExp ]]; then             
    DataSec=$(date +%s --date="$DateExp")
    [[ "$VPSsec" -gt "$DataSec" ]] && EXPTIME="\e[91m[EXPIRADO]\e[97m" || EXPTIME="\e[92m[$(($(($DataSec - $VPSsec)) / 86400))]\e[97m Dias"
    else
    EXPTIME="\e[91m[ S/R ]"
    fi 
    usris="$(cat /etc/SSHPlus/RegV2ray|grep -w "$hostreturn"|cut -d'|' -f2)"
    local contador_secuencial+="\e[93m$hostreturn \e[97m|\e[93m$usris\e[97m|\e[93m $EXPTIME \n"           
          if [[ $i -gt 30 ]]; then
    	      echo -e "$contador_secuencial"
    	  unset contador_secuencial
    	  unset i
    	  fi
    let i++
    done <<< "$IDEUUID"
    [[ ! -z $contador_secuencial ]] && {
    linesss=$(cat /etc/SSHPlus/RegV2ray | wc -l)
    	      echo -e "$contador_secuencial \n Numero de Registrados: $linesss"
    	}
    fi
    }
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    clear
echo -e "\E[44;1;37m            GERENCIAR USUÁRIOS (V2RAY)            \E[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mCRIAR USUÁRIO V2RAY\033[0m"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mREMOVER USUÁRIO V2RAY \033[0m"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mUSUARIOS REGISTRADOS \033[0m"
    echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mRETORNAR AO MENU \033[0m"
    echo ""

echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "; read i

   case "$i" in

      1)
         clear
         uid
         ;;

      2)
         clear
         rmuid
         ;;
      3)
         clear
         info2
         echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
         ;;

      0)
         menu
         ;;

      *)
         echo "opcao invalida, tente de novo"
         ;;

   esac
menu
